In [4]:
 import numpy as np

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:  
    a) 𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2  
    b)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3  
    c)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8  
    d)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4  

    a. Произведение не определено  
    b. Произведение определено, размерность 2х3  
    c. Произведение определено, размерность 8х8  
    d. Произведение определено, размерность 4х4  

2. Найти сумму и произведение матриц  $A = \begin{pmatrix}1 & 2 \\ 3 & 0 \end{pmatrix}$  и  $B = \begin{pmatrix}4 & -1 \\ 0 & 5 \end{pmatrix}$

In [23]:
A = np.array([[1, 2], [3, 0]])

In [24]:
B = np.array([[4, -1], [0, 5]])

In [26]:
A + B

array([[5, 1],
       [3, 5]])

In [27]:
A.dot(B)

array([[ 4,  9],
       [12, -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3𝐴−2𝐵+4𝐶$  для матриц  $A = \begin{pmatrix}1 & 7 \\ 3 & 6 \end{pmatrix}$ ,  $B = \begin{pmatrix}0 & 5 \\ 2 & -1 \end{pmatrix}$ ,  $C = \begin{pmatrix}2 & -4 \\ 1 & 1 \end{pmatrix}$.

4. Дана матрица  $A = \begin{pmatrix}4 & 1 \\ 5 & -2 \\ 2 & 3 \end{pmatrix}$ . Вычислить  $𝐴𝐴^T  и  𝐴^T𝐴$ .

In [29]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [31]:
A_T = A.T

In [33]:
A.dot(A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [35]:
A_T.dot(A).shape

(2, 2)

5. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [58]:
def mult_matrix(m1, m2):
    s=0
    t=[]
    m3=[]
    if len(m1[0]) == len(m2):
        r1=len(m1)
        c1=len(m1[0])   
        r2=c1
        c2=len(m2[0])
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
        return m3
    else:
        print('Вы ввели неподходящие матрицы')
        return False
        
A = np.ones((5, 4))
B = np.ones((4, 3))

mult_matrix(A, B)

[[4.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [4.0, 4.0, 4.0],
 [4.0, 4.0, 4.0]]

6. Вычислить определитель:
  
    a) $ \begin{vmatrix} \sin x & -\cos x \\ \cos x & \sin x \end{vmatrix} $
      
    b) $ \begin{vmatrix} 4 & 2 & 3 \\ 0 & 5 & 1 \\ 0 & 0 & 9 \end{vmatrix} $  
      
    c) $ \begin{vmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{vmatrix} $  

In [61]:
det = np.linalg.det

$ \det(A) = \begin{vmatrix} \sin x & -\cos x \\ \cos x & \sin x \end{vmatrix} = \sin x * \sin x + \cos x * \cos x  = \sin x^2 + \cos x^2$  

In [63]:
B = np.matrix('4, 2, 3; 0, 5, 1; 0, 0, 9')
det(B)

180.0

In [64]:
C = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
det(C)

0.0

7. Определитель матрицы A равен 4.  
Найти:  
a) $ 𝑑𝑒𝑡(𝐴^2) $  
b) $ 𝑑𝑒𝑡(𝐴^𝑇) $  
c) $ 𝑑𝑒𝑡(2𝐴) $  

$ \det(A^2) = \det(A) * \det(A) = 16 $

$ \det(A^T) = \det(A) = 4 $

$ \det(2A) = \det(A) * 2 = 8 $

8. Доказать, что матрица вырожденная:  
  
$ \begin{pmatrix} -2 & 7 & -3 \\ 4 & -14 & 6 \\ -3 & 7 & 13 \end{pmatrix} $  

In [72]:
rank = np.linalg.matrix_rank
inv = np.linalg.inv

In [76]:
A = np.matrix('-2, 7, -3; 4, -14, 6; -3, 7, 13')
print(rank(A))
try:
    print(inv(A))
except:
    print('Нет обратной матрицы')

2
Нет обратной матрицы


Ранг матрицы меньше числа ее строк, и у нее отсутствует обратная матрица => Матрица $ \begin{pmatrix} -2 & 7 & -3 \\ 4 & -14 & 6 \\ -3 & 7 & 13 \end{pmatrix} $ вырождена

9. Найти ранг матрицы:  
  
    a) $ \begin{pmatrix} 1 & 2 & 3 \\ 1 & 1 & 1 \\ 2 & 3 & 4 \end{pmatrix} $  
      
    b) $ \begin{pmatrix} 0 & 0 & 2 & 1 \\ 0 & 0 & 2 & 2 \\ 0 & 0 & 4 & 3 \\ 2 & 3 & 5 & 6 \end{pmatrix} $  

In [68]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
rank(A)

2

In [70]:
B = np.matrix('0, 0, 2, 1; 0, 0, 2, 2; 0, 0, 4, 3; 2, 3, 5, 6')
rank(B)

3