### Ввод матрицы, вычисление среднего значения для наблюдений

In [1]:
import numpy as np

In [4]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Вычитание массивов

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Вычисление ковариации признаков

In [13]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
N = 5 ### Количество измерений
a_covariance = a_centered_sp / (N-1)
a_centered_sp, a_covariance

(8.0, 2.0)

### Альтернативный способ вычисления ковариации

In [14]:
a_tr = a.T
a_tr

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [16]:
a_cov = np.cov(a_tr)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

##### Число, полученное в первом решении (2.0), совпадает с числом с индексом [1, 0] матрицы, полученной из функции вычисления ковариации. Значит значение подсчитано верно.